spring.application.name=problems-MartketPlace
spring.mongodb.uri = mongodb+srv://karthicklimited1234_db_user:XwUkV5RLF5Onvl4K@cluster0.f50pg1u.mongodb.net/?appName=Cluster0
spring.mongodb.database = problem-marketplace